### ISSUE TITLE
Performance problem with large OpenOffice speadsheet

### ISSUE THREAD

**Issue by nfesselet** [roo-rb/roo#113]
After updating roo I noticed a big performance hit on my app and I narrowed it down to the row() method in Roo:OpenOffice which is at least 4 times  slower in version 1.12.0 than in version 1.11.2...

**Comment by stevendaniels** [comment]
Does any one know if this issue still exists in the current version of Roo?

**Comment by csphere** [comment]
Yeah.  We've been trying to find a workaround for this.  We have a .ODS spreadsheet with 67 sheets, 10 columns, and about 60-70 rows per sheet.  Without exaggeration, it takes about 4 hours to run through the sheet once.

Today I explored using `to_xml` on the entire sheet and just parsing the XML, but I called `to_xml` at least an hour and a half ago and it's still running so that doesn't seem too promising.

Interestingly enough, I removed all logic and operations from our method using Roo, and left behind only the calls to `each_with_pagename` and `each_with_index`, but that also took about 4 hours even just looping through the sheets/rows and not doing anything.

This gem has exactly what we need but I'm afraid it would be hard for us to produce a good excuse for spending this long on ~5000 rows.  Pulling my hair out.

**Comment by stevendaniels** [comment]
@csphere : Are you using the RubyGems version (1.13.2) or the github version of Roo (2.0.0)?
Any chance you could provide me with a copy of the spreadsheet?

**Comment by csphere** [comment]
System:
```
MacBook Pro Retina
2.7 GHz i7
16GB DDR3
```
Versions:
```
$ gem -v
2.4.1
$ echo 'Roo::VERSION' | rails c
Loading development environment (Rails 4.1.4)
Switch to inspect mode.
Roo::VERSION
"1.12.1"
```

Code:
```
roo = Roo::Spreadsheet.open(path)
roo.each_with_pagename do |name, sheet|
  sheet.each_with_index do |row, i|
    # do stuff
  end
end
# 4 hours later...
```

Spreadsheet: ([mockup](https://docs.google.com/spreadsheets/d/1sS-6G2Wnav68x5XODVulRrPJQdeQDW6sUBTtRHGpsBg/edit?usp=sharing))

`File > Download As > OpenDocument Format (.ods)`

**Comment by stevendaniels** [comment]
Right now, using roo in a console (irb, pry, etc.) might take long because of Roo's ```inspect``` method. See #50 for more details.

If you don't need the return value of  ```each_with_pagename```, then you should avoid returning it in the console. 

Wrapping the ```Roo``` code you want in a function with a ```nil``` return might be much faster, or you can try adding multiple statements to prevent the console from displaying ```inspect``` value.

    roo = Roo::Spreadsheet.open(path); nil
    roo.each_with_pagename do |name, sheet|
      sheet.each_with_index do |row, i|
        # do stuff
     end
    end; nil
