### ISSUE TITLE
Quote escaping for Roo::Base#cell_to_csv

### ISSUE THREAD

**Issue by awright415** [roo-rb/roo#158]
Ran into an issue with an .xlsx file that has quotation marks within a text column. It looks like maybe the mechanism for escaping double quotes in #cell_to_csv doesn't do what it's intended to.

Calling `onecell.tr('"', '""')` doesn't seem to convert a single double quote into two double quotes. Perhaps gsub would be a better option for handling CSV's quote escaping?

**Comment by stevendaniels** [comment]
That's a good idea. Could you submit a pull request with your proposed changes?

**Comment by stevendaniels** [comment]
@awright415 
I just did a check with a sample ```ods``` file.

The results are [here](https://gist.github.com/stevendaniels/f70134e8bfc06b3e3ba4)

Is this the expected behavior?

**Comment by samhowley** [comment]
@stevendaniels I don't believe that is the required behavior.

Since CSV requires double quotes to be escaped via repeating them eg "" not via a backslash eg. \"
we would not want the output to be as the gist shows : 

"\"id\",\"quote\"\n1,\"\"Hello\"\"\n2,\"\"world\"\"\n"

but rather : 

"\"id\",\"quote\"\n1,\"\"\"Hello\"\"\"\n2,\"\"\"world\"\"\"\n"

The Hello and world string should be wrapped in quotes and then have another two quote characters each side (which repesents a single quote embedded in the string).

I believe the tr calls in cell_to_csv need to be changed to gsub in order to properly escape double quote characters.
 
TR seems to be returning a single double quote character in the output string no matter how many appear in the to_str.

I will create a pull request with the changes.

TR and GSUB produce different results : 

 > r = %(TORTILLAS FLOUR 8" s ).tr('"', '""')
 => "TORTILLAS FLOUR 8\" s " 

> r = %(TORTILLAS FLOUR 8" s ).gsub('"', '""')
 => "TORTILLAS FLOUR 8\"\" s "

**Comment by stevendaniels** [comment]
@samhowley Thanks for looking into this issue. I spent some time reading Ruby's  `String` [docs](http://ruby-doc.org/core-2.2.1/String.html) (my favorite Ruby-doc page), and I think I finally figured out the issue. From the description it sounds like `tr` is similar to `gsub`, but there are some major differences.

`tr` works on a character by character basis. It doesn't seem possible to use `tr` to replace one character with more than one character. Here's a clearer example of `tr`'s usage:

    %(TORTILLAS FLOUR 8" s ).tr('"', '"$')
    # => "TORTILLAS FLOUR 8\" s "

    %(TORTILLAS FLOUR 8" s ).tr('"s', '"$')
    # => "TORTILLAS FLOUR 8\" $ "

    %(TORTILLAS FLOUR 8" s ).tr('"sS', '"$')
    # => "TORTILLA$ FLOUR 8\" $ "

`gsub` is definitely what `roo` should be using.
