### ISSUE TITLE
Maybe extract all formats?

### ISSUE THREAD

**Issue by simonoff** [roo-rb/roo#187]
@stevendaniels What do you think? May be would be better to make `roo-core` and `roo-xlsx`, `roo-odf`, `roo-csv`?

**Comment by stevendaniels** [comment]
I don't think extracting all of them helps the gem users that much. What are the advantages? What problem does extracting all formats solve?

I think extracting ``roo-google`` made sense because it uses a lot of code that is unrelated to other formats. Extracting ``roo-xls`` made sense because of the license issue.

**Comment by Empact** [comment]
I agree with @stevendaniels there's not much benefit to splitting further.
