### ISSUE TITLE
Zip::Error: Zip end of central directory signature not found

### ISSUE THREAD

**Issue by TheRealGuardDogGPS** [roo-rb/roo#203]
I looked over the tests for this gem. It doesn't use any xls files as examples, even though it says it supports xls files. I read on stackoverflow you can force xlsx on the xls file by using the extension option:

Roo::Spreadsheet.open( "/Users/merlino/projects/internal_system/lib/data/excel/new 09-2014/MFOREC11.xls", extension: :xlsx)
Zip::Error: Zip end of central directory signature not found

But it gives the above error. Why does this error occur?

**Comment by stevendaniels** [comment]
Hi. In the beta version of Roo, legacy `xls` support has been extracted into the [roo-xls](https://github.com/roo-rb/roo-xls) gem. If you're dealing with `xls` files, you will need to install that gem, too. This change is mentioned in the `Readme`, but perhaps it should be changed to be even more explicit.

This error is probably being caused by you trying to open an `xls` file using an `xlsx` extension.  Based on #202, it sounds like you have a directory of files that might have the wrong extension. In that case, I suggest trying to open the files using the xlsx extension option and falling back to roo-xls.

    require 'roo'
    require 'roo/xls'
    begin
      Roo::Spreadsheet.open(filepath, extension: :xlsx)
    rescue Zip::Error
      Roo::Spreadsheet.open(filepath)
    end

One other thing to look out for, it sounds like your directory may contain a list of Excel2003XML files, too. 
From my testing, the following should work for all Excel spreadsheet types.

**Comment by cisolarix** [comment]
solved my problem. thanks @stevendaniels

**Comment by diam** [comment]
> I looked over the tests for this gem. It doesn't use any xls files as examples, even though it says it supports xls files. I read on stackoverflow you can force xlsx on the xls file by using the extension option:
> 
> Roo::Spreadsheet.open( "/Users/merlino/projects/internal_system/lib/data/excel/new 09-2014/MFOREC11.xls", extension: :xlsx)
> Zip::Error: Zip end of central directory signature not found
> 
> But it gives the above error. Why does this error occur?

Solved my problem too, thanks @stevendaniels!
-- Maurice
