### ISSUE TITLE
New line in cell can create _x000D_

### ISSUE THREAD

**Issue by yinyangxu** [roo-rb/roo#223]
Some types of new lines in excel-cell looks ok in excel, but adds
_x000D_ when imported with Roo::Excelx

which much like the issue here  https://github.com/hadley/readxl/issues/51

**Comment by stevendaniels** [comment]
Can you create a gist for this issue ([sample gist](https://gist.github.com/stevendaniels/98a05849036e99bb8b3c))? Here are some instructions for creating such a gist. 

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

**Comment by yinyangxu** [comment]
Hi, here is my gist https://gist.github.com/yinyangxu/4fb84a0c6fd44784c3a4. Because of my network problem, I can not upload the bug xlsx file right now. I will upload it later.

**Comment by stevendaniels** [comment]
@yinyangxu Actually, Roo didn't add the `_x000D_`, it was in the XML inside of your sample XLSX file. The program you used to create this Excel file added these values. What program was used to create the file?

I've submitted a pull request that fixes the issue.

**Comment by simonoff** [comment]
What the reason then in #231 ?

**Comment by stevendaniels** [comment]
I don't know for certain what causes the `_x000D_` issue, but it's not Roo. It's possibly caused by the program that created the `xlsx` file. I saw related issues in [OOXML here](http://www.robweir.com/blog/2008/03/ooxmls-out-of-control-characters.html). 

From my understanding, these characters are invalid representations of normal strings or characters. In this case `_x000D_ == \n` . 

It's also possible that more of these issues might appear in the future. It seems pretty rare though.

**Comment by yinyangxu** [comment]
@stevendaniels I use 'writeexcel' lib to create the Excel file which contains the new line in cell. Then i open it use MS Excel 2007 and save it as xlsx format. It's ok when reading the xlsx file with python xlrd lib or MS Excel 2007, but it shows the bug character _x000D_  when i using roo lib.

**Comment by stevendaniels** [comment]
This sounds like it may be an issue with that library (and the library it is based on). 
Can you post a sample of the code you use when creating the line using writeexcel?

**Comment by yinyangxu** [comment]
Maybe. But the [bug.xlsx](https://gist.github.com/yinyangxu/4fb84a0c6fd44784c3a4/raw/921fc65b764391bd2c2b65b552d59097d3378262/bug.xlsx)  file looks ok when reading it with MS Excel 2007 or python xlrd lib except for roo. 
I just use "worksheet.write(row, 8,  line)" to create a xls format Excel file. Then open it with MS Excel 2007 and add some new line in a cell. Finally i save it as xlsx format. Is it possible that the problem results from converting xls to xlsx?

**Comment by stevendaniels** [comment]
@yinyangxu Sounds to me like xls to xlsx conversion with Chinese text might be what's causing the issue. Thanks for your help.

I've merged a fix to master.

**Comment by kaluznyo** [comment]
I Just have same bug, but with Excel 2011 ou 2016 for mac. I create a file, with 2 sheet, One with data, a text with new line. In my first file i use VLOOKUP to get text from the other sheet. I save with xls then xlsx.
And this add _X00D_ (I can see it directly in worksheets/sheet1.xml. The fix (https://github.com/roo-rb/roo/pull/231) don't work because it's not in sharing string, but directly in sheet. If I use your patch in SheetDoc.extract_celles, it's work fine (But I don't know if it's the good place to do this)

Could you use this patch for all sheet ?

**Comment by jarredholman** [comment]
This issue was fixed incorrectly.
\_x000D_ is an escape for \u000D aka Carriage Return (\r not \n)

**Comment by jcnaud** [comment]
This issue was fixed incorrectly.

I have the save ploblem and the issue concern the "\r" implementation on xlsx. 
**Case 1 with "\n":**
When i write in cell: "KM\nSTART"
On LibreOffice , i have : 
```
"KM
START"
```
On Excel i have:
```
KMSTART
```

**Case 2 with "\r\n":**
On LibreOffice i have : 
```
"KM_x000D_
START"
```
On Excel i have:
```
KMSTART
```
