### ISSUE TITLE
excelx : pad_cells shouldn't be true by default ?

### ISSUE THREAD

**Issue by fabien-michel** [roo-rb/roo#249]
Using ```xlsx.each_row_streaming```, blank cells are excluded from the row array.
Surprisingly i discover **an undocumented** pad_cells option that allow to keep blank cells in row array.
I suggest to make this option true by default, for me it's the expected behavior.

**Comment by stevendaniels** [comment]
Thanks for raising this issue. I'd noticed the `pad_cells` option, but I didn't realize it was so poorly documented. Would you be willing to add a section to the Readme?


I have mixed feelings about the `pad_cells` option. On the one hand, I agree with you: if you don't expect it, the behavior is a bit weird.

The option can be extremely useful in some cases. Sometimes a spreadsheet file gets saved with a lot empty rows and columns (I've seen cases with thousands and empty rows and empty columns). In those cases, opening the file in Roo would be slow and take a lot of memory because it would create objects for each of those empty cells. If the `pad_cells` option is false or nil, then those cells to get skipped, which saves processing time and memory.

As for your suggestion, making the default option true, I have the following thoughts:

1. Changing this option, in my opinion, would require a major version change. 
2. As is, I feel this option solves a bigger problem than it solves. With better documentation, other users would be less likely to encounter the same confusion.
3. I'm working on some relatively big changes to the way Roo handles configurations. As part of addressing #242, I'm working on adding a `Roo.configure` method. This would allow for the the familiar configuration block used by lots of gems.

e.g.

    # config/initializers/roo.rb
    
    Roo.configure do |config|
      config.pad_cells = true
    end


====

I also looked into the origin of this option. For the curious, the change first occured in a [fork of Roo] (https://github.com/roo-rb/roo/commit/91c9f9b34838f6a1e9ba16246a215f0c9bb15601) that was eventually merged back into the project.

**Comment by fabien-michel** [comment]
Thanks for your explanation, I agree with you.
