### ISSUE TITLE
The .row method olways return only 40 rows

### ISSUE THREAD

**Issue by THPubs** [roo-rb/roo#261]
Tried several spreadsheets. All contain between 150 to 250 rows. But when I run `xl.row('E')` It always give only 40 rows.

**Comment by stevendaniels** [comment]
I'm not sure I fully understand the issue. `xl.row(5)` should return an array of the columns, not rows. 

Could you provide an example of the issue using a gist ([sample gist](https://gist.github.com/stevendaniels/98a05849036e99bb8b3c))? Here are some instructions for creating such a gist. 

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

**Comment by THPubs** [comment]
Ah sorry it's columns. Not rows. It's only giving 40 columns where's there more than that. I didn't add this in my code yet. Still experimenting in the console before starting. I added the console output to a gist : https://gist.github.com/THPubs/2c1c200a2be6edd2a57d  And attaching the stripped down version of the excel file here : https://drive.google.com/file/d/0B_qbiPxuAyj7MTJkdms4M2M1Vm8/view?usp=sharing

**Comment by stevendaniels** [comment]
Thanks. I looked into the code and noticed the following:

1. You should use an integer when calling the `.row` method.
2. The spreadsheet you provided has 43 columns, but three of them are empty; that's why `row` is returning 40 columns instead of 43. By default, Roo will ignore empty columns and rows.

I think it's worth considering having an option for not ignoring empty columns and rows.
