### ISSUE TITLE
.labels

### ISSUE THREAD

**Issue by rogsmith** [roo-rb/roo#276]
NoMethodError: undefined method `split' for nil:NilClass
lib/roo/excelx/workbook.rb:35:in `block in defined_names'

**Comment by stevendaniels** [comment]
I'd really need to see a copy of your excel file in order to understand why this isn't working properly.Can you create a gist for this issue ([sample gist](https://gist.github.com/stevendaniels/98a05849036e99bb8b3c))? Here are some instructions for creating such a gist. 

1. [Create a gist](https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

**Comment by stevendaniels** [comment]
@rogsmith Any chance I could see a sample of the file that caused the error you encountered?

**Comment by stevendaniels** [comment]
Please reopen if the issue occurs again.

**Comment by md5** [comment]
I just ran into a sheet exhibiting this issue. The `definedName` in question looked like `Sheet1!#REF`, so the split on `!$` only returns a single item, leaving `coordinates` set to `nil` and causing the exception mentioned above when `nil#split` is called`.

**Comment by md5** [comment]
Here's the simplest fix I can see for this:

```diff
diff --git a/lib/roo/excelx/workbook.rb b/lib/roo/excelx/workbook.rb
index 7ef841f..bb79e02 100644
--- a/lib/roo/excelx/workbook.rb
+++ b/lib/roo/excelx/workbook.rb
@@ -32,10 +32,12 @@ module Roo
         Hash[doc.xpath('//definedName').map do |defined_name|
           # "Sheet1!$C$5"
           sheet, coordinates = defined_name.text.split('!$', 2)
+          next if coordinates.nil?
+
           col, row = coordinates.split('$')
           name = defined_name['name']
           [name, Label.new(name, sheet, row, col)]
-        end]
+        end.compact]
       end
 
       def base_date
```

If you want to actually represent invalid labels in the hash returned by `defined_names`, then the `Label` class would need to be enhanced to allow it to represent these invalid labels. The parsing would also need to be changed to split on `!` instead of `!$` and to deal with the reference after the `!` consistently. To be honest, it's probably not a bad idea to use common code for parsing that reference anyways instead of ad hoc code in the `defined_names` method.

**Comment by md5** [comment]
@stevendaniels Do you want me to open a PR with my suggested change?
