### ISSUE TITLE
Encoding error with csv since 2.7.0

### ISSUE THREAD

**Issue by kaluznyo** [roo-rb/roo#371]
Hi,

Since version 2.7.0, my csv file create with excel (office mac 2016) can't be open with roo.

I do 

`Roo::CSV.new(file.path, {csv_options: {col_sep: ';', encoding: Encoding::ISO_8859_1}`

This raise error "invalid byte sequence in UTF-8" with backtrace 

`/Users/olivierkaluzny/.rvm/gems/ruby-2.3.1/gems/roo-2.7.0/lib/roo/csv.rb:101:in `set_row_count'
     # /Users/olivierkaluzny/.rvm/gems/ruby-2.3.1/gems/roo-2.7.0/lib/roo/csv.rb:66:in `read_cells'
     # /Users/olivierkaluzny/.rvm/gems/ruby-2.3.1/gems/roo-2.7.0/lib/roo/base.rb:145:in `row'
`

**Comment by stevendaniels** [comment]
Thanks for reporting the issue. I think we need to pass `@csv_options` into the `CSV.readlines`

I'm having trouble reproducing the issue because I don't have any iso_8859_1 files that cause the error. Can you provide one in a gist?

Here are some instructions for creating such a gist. 

1. Create a gist (https://gist.github.com) with code that creates the error.
2. Clone the gist repo locally, add a stripped down version of the offending spreadsheet to the gist repo, and push the gist's changes master.
3. Paste the gist url here.

I think the following test case will cause the error if it has the right source file 
```
  def test_iso_8859_1
    file = File.open(File.join(TESTDIR, "iso_8859_1.csv"))
    expected_result = 42 # TODO: replace with actual result
    options = { csv_options: { encoding: Encoding::ISO_8859_1 } }
    workbook = Roo::CSV.new(file.path, options)
    result = workbook.last_column
    assert_equal expected_result, result
  end
```

**Comment by stevendaniels** [comment]
@kaluznyo: Please let me know if #372 fixes your issue.

**Comment by kaluznyo** [comment]
Yep, your commit fix issue. Thanks !

**Comment by stevendaniels** [comment]
@kaluznyo: Can you please provide a sample file that can trigger the error? I'd like to avoid having a similar regression in the future.

**Comment by kaluznyo** [comment]
https://gist.github.com/kaluznyo/8cfc794ff54f9077703f84421519d91b

**Comment by stevendaniels** [comment]
Thanks. I'll be pushing out a new version soon.

**Comment by danielparker00** [comment]
I have still encoding issue.
``
def read
  data = Roo::CSV.new("test.csv", csv_options: {encoding: Encoding::ISO_8859_1})
end
``
If CSV file is encoded by UTF-8,  unknown character is shown.
After chane csv_option to Encoding::UTF_8, Exception is raised when open the ISO_8859_1 encoded file like "invalid byte sequence in UTF-8".

How can I read any encoded file without any error?
Thanks.

**Comment by tgturner** [comment]
@danielparker00 What version of Roo are you using? Can you provide a file that reproduces the error?
