### ISSUE TITLE
Opening CSV from a URI is failing

### ISSUE THREAD

**Issue by kiranchangsathya** [roo-rb/roo#374]
with the latest version 2.7.1, opening a CSV from a URI is not working. Getting "No such file found" error. However this was fine with 2.5.1 or 2.6.0, so had to lock down these version.

**Comment by iainbeeston** [comment]
I'm seeing this as well. I've tracked down the issue to c107923b2db18595e9cbbec87aab6dc0de9cbb70. Before that commit, the only place in the code that loaded csv data was `Roo::CSV.each_row()`, and that method had separate code for handling data from uris, streams or local files. Everything else in `Roo::CSV` would to call that method to access csv data, and so every other method didn't need to know where the data was coming from.

In c107923b2db18595e9cbbec87aab6dc0de9cbb70, `Roo::CSV. read_cells()` was refactored and some of the code was moved into two new methods: `Roo::CSV.set_column_count()` and `Roo::CSV.set_row_count()`. But instead of calling `Roo::CSV.each_row()` they have their own code for loading the csv data, and can't handle loading data from a uri.

The important bit that `Roo::CSV.set_column_count()` and `Roo::CSV.set_row_count()` are missing is that for uris `Roo::CSV.each_row()` downloads the csv file before parsing it. The code for this is in `Roo::CSV.each_row_using_tempdir()` and it looks like it could be refactored so that it can be reused by the other methods as well.

**Comment by iainbeeston** [comment]
It's possible that loading csv data from a stream is broken as well, but I haven't been able to test that

**Comment by cthornbe** [comment]
we have the same issue, I reverted back to 2.6.0

**Comment by sarojkh** [comment]
We had similar issue as well. Reverted back to 2.6.0 to fix it.

**Comment by matiasgarcia** [comment]
Has anyone found a workaround for this? Looks like downgrading roo to 2.6.0 works, but 2.7.0 is way more performant than 2.6.0
