### ISSUE TITLE
Suggestion: Add small section to README about Excel Date Serialization

### ISSUE THREAD

**Issue by sunnyrjuneja** [roo-rb/roo#390]
Hi roo maintainers,

Firstly, thank you so much for such an incredible gem. I tried several solutions and none worked as well as roo. I really appreciate your hard work.

I had a minor issue when reading xlsx files. In my xlsx files, the date column was formatted to show dates like: "06/30/2017". When I read them from the xlsx, they showed 42916. I spent a few hours trying to figure out what was goign on. I eventually typed the right combination of google terms to discover that Excel serializes dates as the number of days from Jan 0, 1900 (yes day 0) see http://www.cpearson.com/excel/datetime.htm.

As someone with very little experience working with xlsx files, this came to a surprise but immediately solved my problem when I followed the advice described in this Stack Overflow post to do the following http://stackoverflow.com/questions/10559767/how-to-convert-ms-excel-date-from-float-to-date-format-in-ruby.

```ruby
irb(main):021:0> Date.new(1899, 12, 30) + 42916.to_f
=> #<Date: 2017-06-30 ((2457935j,0s,0n),+0s,2299161j)>
```

My suggestion is one of the two following:

* Add something to the README about working with excel dates
* Provide a helper function that converts serial date serialization to Date objects.

If you would like, I can provide a gist as described in the template. I didn't think it was necessary but perhaps you feel differently.

Thanks again for the great project. I'm happy to implement either of my suggestions.

**Comment by chopraanmol1** [comment]
@sunnyrjuneja can you provide sample xlsx file?

roo does support date serialization, it may be an issue about roo not recognizing the format as valid date format.

**Comment by sunnyrjuneja** [comment]
@chopraanmol1 here is a test case for you. fyi, opening the report and saving it "fixes" the issue.
[test.xlsx](https://github.com/roo-rb/roo/files/2590454/test.xlsx)

**Comment by chopraanmol1** [comment]
@sunnyrjuneja Thank you for providing a sample file. I'll like to point out the following:
1. Excelx client generating the xlsx file is responsible to define the custom format/style. In absence of respectively defined format, excelx client uses predefined style/format (check `Roo::Excelx::Format::STANDARD_FORMATS`)
2. Provided sample file doesn't use one of the predefined format's id (i.e. 30) and doesn't define a custom format for the same id, which makes the result ambiguous.
3. If you try to open the same file in different excel client then displayed result is different as well. e.g. LibreOffice displays date whereas Google 's spreadsheet displays number.

I think the source of the problem is Excelx client generating the file. I think you can do the following things:
1. If you are aware of the excel client generating file kindly report them this issue.
2. If reporting is not possible and the excel client always generate the same numFmtId (i.e. 30 for "dd/mm/yyyy") you can register an entry in `Roo::Excelx::Format::STANDARD_FORMATS`:
```
Roo::Excelx::Format::STANDARD_FORMATS[30] = "dd/mm/yyyy"
```

**Comment by sunnyrjuneja** [comment]
@chopraanmol1 Thanks for looking into this! Excel parsing is a complicated beast, appreciate you taking the time.

I unfortunately have no control over the source excel. I'm currently using the function above for columns I know are a date. Feel free to close this issue if there is no fix planned.

**Comment by chopraanmol1** [comment]
@sunnyrjuneja on side note you should not use hard coded base date. Try calling `workbook.base_date` on roo excelx instance instead. This method also considers https://msdn.microsoft.com/en-us/library/ff530155(v=office.12).aspx

Out of curiosity are you aware about the excel client(down to particular version will be better) generating your respective source file?

**Comment by sunnyrjuneja** [comment]
@chopraanmol1 That's good advice, thank you! I unfortunately have no context or contact what so ever. It's a legacy system which we don't have access to except for a web interface.
