### ISSUE TITLE
Roo::CSV Row Method Not Returning Entire Row

### ISSUE THREAD

**Issue by HunterFortuin** [roo-rb/roo#395]
Hi! I noticed today that if there's a cell that has a nil value in a row, the `row` method of a `Roo::CSV` object doesn't return the entire row. Here's the gist for the issue: [https://gist.github.com/HunterFortuin/5c2a79a95cc0c023e0028a0729da46f9](https://gist.github.com/HunterFortuin/5c2a79a95cc0c023e0028a0729da46f9).

Instead of the return of:

```
=> [nil, "Specimen Label"] 
```

It should be returning:

```
=> [nil,
 "Specimen Label",
 "Length (in)",
 "Width (in)",
 "Thickness (in)",
 "Mass (g)",
 "Density (lb/cuft)",
 "Compressive Modulus (psi)",
 "Compressive Stress at 15% Compression (psi)",
 "Compressive Load at 15% Compression (lbf)",
 "Compressive Extension at 15% Compression (in)",
 "15% Extension (in)",
 "Notes on Specimen"]
```

**Comment by ashjambhulkar** [comment]
@HunterFortuin ,  I dont know how but when I tried to run your csv file on my system, it is running perfectly fine.

```
mruduls-MBP:dobozapi doboz$ irb
Welcome to IRB. You are using ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]. Have fun ;)
>> require 'roo' #=> true
>> require "roo/version" #=> true
>> Roo::VERSION #=> "2.7.1"
>> Dir.pwd #=> "/Users/doboz/Desktop/ashish/dobozapi"
>> spreadsheet = Roo::CSV.new('/Users/doboz/Downloads/xyz.csv')
=> <#Roo::CSV:1777464222556350 @filename @options @cell @cell_type @cells_read @first_row @last_row @first_column @last_column @header_line>
>> spreadsheet.row(11)
=> [nil, "Specimen Label", "Length (in)", "Width (in)", "Thickness (in)", "Mass (g)", "Density (lb/cuft)", "Compressive Modulus (psi)", "Compressive Stress at 15% Compression (psi)", "Compressive Load at 15% Compression (lbf)", "Compressive Extension at 15% Compression (in)", "15% Extension (in)", "Notes on Specimen"]
>> 
```

**Comment by jchan172** [comment]
I'm getting the same result as @HunterFortuin running `irb` using ruby 2.3.3 on my Mac. Also using Roo 2.7.1. After poking around a little bit, it appears that Roo is using the first row to determine how many elements per array. Opening your .csv file, it appears that you only have 2 elements in the first row, but there are 12 columns. To get things to work, I added enough commas in the first row to match the largest number of columns in any of the rows.
So, instead of 
`Experiment Identifier,INT-PGVL666`
use
`Experiment Identifier,INT-PGVL666,,,,,,,,, `
in your .csv file as the first row. Then, you'll be able to access the later ones.

**Comment by peichman-umd** [comment]
@HunterFortuin, I encountered the same problem during an upgrade of another piece of software that used Roo. As part of that upgrade, the new version was using the latest Roo (2.7.1 as of this writing). I found that if I pinned the version to 2.6.0 in my Gemfile and Gemfile.lock, I am not getting the truncated rows.

**Comment by chopraanmol1** [comment]
Duplicate https://github.com/roo-rb/roo/issues/375

Fixed by https://github.com/roo-rb/roo/pull/406 (in master)
