### ISSUE TITLE
NoMethodError if the sheet contains comments

### ISSUE THREAD

**Issue by Mifrill** [roo-rb/roo#418]
1. An error occurs while reading if the document contains comments.
Upon repeated use, the reading works without errors.

![screenshot from 2018-03-03 15-08-56](https://user-images.githubusercontent.com/23525618/36933056-db2399b0-1ef4-11e8-859d-71590fe461d5.png)

2. Gist: https://gist.github.com/Mifrill/b8448c9adda997b664a4cd973cd09b97

**Comment by Mifrill** [comment]
It looks like an error in the last_row method

```
# lib/roo/base.rb, lines 118-125:

  %w(first_row last_row first_column last_column).each do |key|
    class_eval <<-EOS, __FILE__, __LINE__ + 1
      def #{key}(sheet = default_sheet)                                   # def first_row(sheet = default_sheet)
        read_cells(sheet)                                                 #   read_cells(sheet)
        @#{key}[sheet] ||= first_last_row_col_for_sheet(sheet)[:#{key}]   #   @first_row[sheet] ||= first_last_row_col_for_sheet(sheet)[:first_row]
      end                                                                 # end
    EOS
  end
```

Here the use of text method it's not obvious, can you clarify the situation where exactly text method is called?

**Comment by chopraanmol1** [comment]
I tried looking into this issue, but seeing the backtrace it seems the problem lies in spreadsheet gem.

I found a ticket in spreadsheet gem addressing a similar issue. You can look into it.

https://github.com/zdavatz/spreadsheet/issues/221

For now I'm closing this ticket, let me know if the above solves your issue or not.
