### ISSUE TITLE
Error when opening file with expand_merged_ranges and parse with clean option

### ISSUE THREAD

**Issue by tbonz** [roo-rb/roo#506]
### Steps to reproduce

1. Example code:
```ruby
require 'roo'
xl = Roo::Spreadsheet.open('test.xlsx', expand_merged_ranges: true)
xl.parse(one: /one/i, two: /two/i, clean: true)
```
2. Test spreadsheet: [test.xlsx](https://github.com/roo-rb/roo/files/3351758/test.xlsx)

### Issue
The example fails with an exception: **undefined method `value' for nil:NilClass (NoMethodError)**

### System configuration
**Roo version**: 2.8.2

**Ruby version**: 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]

**Comment by ttilberg** [comment]
Notice that the process of `expand_merged_ranges` will explicitly create `cells[dst] = nil` if the `src` is nil (which otherwise does not show up in `cells`:

![image](https://user-images.githubusercontent.com/7969650/60537522-58e35400-9cce-11e9-93ee-34c579fada58.png)

So, the source of the issue seems to be related to `expand_merged_ranges` explicitly creating `nil` values in the cells hash when an empty (nil) cell is merged.

**Comment by tbonz** [comment]
@chopraanmol1 I see ttilberg has a merge ready to go that will solve this issue.  This would be a great update if you were able to get it published soon.  Thank you!
