### ISSUE TITLE
Roo::Base autoloading.

### ISSUE THREAD

**Issue by Exoth** [roo-rb/roo#72]
Is there any reason why `Roo::Base` is being autoloaded instead of being required? Any of `Roo::<something>` classes anyway depend on `Roo::Base`, so if I use Roo in any way, `Roo::Base` will have to be loaded.

The problem is that without manually requiring `Roo::Base` I can't set a `rescue ::Zip::ZipError`, which is quite strange.

**Comment by stevendaniels** [comment]
@simonoff , What are the benefits for using autoload vs. require in this case?

**Comment by simonoff** [comment]
@stevendaniels in any case autoload is deprecated. Before it was usable if you need load only a part of functionality. For example you working only with xlsx and not need to load google spreadsheets code.
I think we can fix it by require `Roo::Base` and extract other parts into separate gems.

**Comment by stevendaniels** [comment]
Which parts would you extract into separate gems?

**Comment by Empact** [comment]
@Exoth you can also solve this issue by requiring the specific type you're using, which in this case must be `require 'roo/excelx'` or `require 'roo/open_office'`. Alternatively you can load the 3rd-party code that we're relying on,`require 'zip/filesystem'`. Have you tried those?

@simonoff I prefer to move off of deprecated code immediately, but autoload isn't deprecated - it's "future deprecated." We'll get much stronger signals to move away long before it actually happens, and we can drop it then if necessary (e.g. when we start to see release candidates for ruby 3). There will probably also be a "right answer" alternative that emerges by the time removal is actually occurring. https://www.ruby-forum.com/topic/3036681

IMO autoloading still makes sense because of the different dependencies that each type relies on. Now that roo-google and roo-xls have been split out, the benefits are less significant, but they're still present - e.g. it saves users from pulling in zip dependencies when not necessary.

**Comment by Exoth** [comment]
Exceptions that can occur during using Roo should be considered a part of Roo main usage interface. I'm ok with autoload of Roo::Base, as autoload by itself (if used properly) doesn't bring any problems, but zip/filesystem is both not autoloaded and not required as a part of Roo require, so I still consider this a bug.

**Comment by stevendaniels** [comment]
Requiring Roo::Base was fixed in [this commit](https://github.com/roo-rb/roo/commit/df1823cf1015b385e99d49b8c400866795d4ffa9). The current version of Roo includes the fix.

@Exoth Can we close this issue?

**Comment by Exoth** [comment]
Yes, that should fix the problem, thanks.
